image:
  tag: latest
  pullPolicy: Always
  registry: harbor.dev-se.telia-ck8s.com
  
containers:
  anon_proxy_app:
    imageName: anon-proxy
    name: "anonymization-proxy"
    version: latest

    replicas: 1
