image: harbor.dev-se.telia-ck8s.com/knowledge-dev/anon-proxy:v1.0.0

resources:
  # Most Welkin clusters require the application to specify resources.
  # Otherwise, complying with capacity management policies becomes difficult.
  # Adjust the following two values based on load-testing or production data.
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

podSecurityContext: {}
  # fsGroup: 2000

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  runAsNonRoot: true
  seccompProfile:
    type: "RuntimeDefault"
    readOnlyRootFilesystem: true
    runAsUser: 1000

networkPolicy:
  ## @param networkPolicy.enabled Enable creation of NetworkPolicy resources
  ##
  enabled: true
  ## @param networkPolicy.ingressNSMatchLabels Labels to match to allow traffic from other namespaces
  ## Empty means accept from all namespaces.
  ## @param networkPolicy.ingressNSPodMatchLabels Pod labels to match to allow traffic from other namespaces
  ingressNSMatchLabels: {}
  ingressNSPodMatchLabels: {}
