apiVersion: apps/v1
kind: Deployment
metadata:
  name: anonymization-proxy
  labels:
    app: anonymization-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: anonymization-proxy
  template:
    metadata:
      labels:
        app: anonymization-proxy
    spec:
      containers:
        - name: anonymization-proxy-container
          image: harbor.dev-se.telia-ck8s.com/knowledge-dev/anon-proxy:latest
          ports:
            - containerPort: 80
