apiVersion: apps/v1
kind: Deployment
metadata:
  name: anonymization-proxy-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: anonymization-proxy-dev
  template:
    metadata:
      labels:
        app: anonymization-proxy-dev
    spec:
      containers:
        - name: anonymization-proxy-dev
          image: 'dummy:latest'
